---
layout: base-page
title: About
permalink: /about/
bodyClass: page
nav_items: [concepts, posts,stats, feedback]
show_header_meta: true
---
:page-liquid:

== About Electropedia

Electropedia is produced by the http://www.iec.ch/[IEC], the world’s leading organization that prepares and publishes International Standards for all electrical, electronic and related technologies – collectively known as “electrotechnology”. Electropedia (also known as the "IEV Online") contains all the terms and definitions in the International Electrotechnical Vocabulary or IEV which is published also as a set of publications in the IEC 60050 series that can be ordered separately from the http://www.iec.ch/dyn/www/f?p=103:22:0::::FSP_ORG_ID,FSP_LANG_ID:1231,25[IEC webstore].

Electropedia is the world's most comprehensive online terminology database on “electrotechnology”, containing more than 22 000 terminological entries in English and French organized by subject area, with equivalent terms in various other languages: *Arabic*, *Chinese*, *Czech*, *Finnish*, *German*, *Italian*, *Japanese*, *Korean*, *Norwegian* (Bokmål and Nynorsk), *Polish*, *Portuguese*, *Russian*, *Serbian*, *Slovenian*, *Spanish* and *Swedish* (coverage varies by subject area).

The world’s experts in electrotechnical terminology work to produce Electropedia under the responsibility of http://www.iec.ch/tc1[IEC Technical Committee 1] (Terminology), one of the 204 IEC http://www.iec.ch/dyn/www/f?p=103:6:0[Technical Committees and Subcommittees].

== Please help us improve Electropedia!

If you have any comments or suggestions on Electropedia or specific terms and definitions, we want to hear from you. Please send an e-mail to mailto:terminology@iec.ch[terminology@iec.ch].

Can I use a term or definition from Electropedia? Yes!

While Electropedia’s structure and content are http://www.iec.ch/about/copyright/copyright-db_entry.htm[copyright] IEC, we encourage the use, referencing or citation of Electropedia for the purpose of identifying or clarifying the meaning of electrotechnical concepts, terms and symbols and their use in manuals, diagrams and equipment. We only ask that IEC is referenced as the source. For users wishing to duplicate Electropedia or use large portions for commercially or for free sharing, mailto:custserv@iec.ch[please contact the IEC].

== Copyright

(C) {{ site.time | date: "%Y" }} International Electrotechnical Commission.

All rights reserved. Unless otherwise specified, no part of this
site or its documents may be reproduced or utilized otherwise in any form or by any
means, electronic or mechanical, including photocopying, or posting on the
internet or an intranet, without prior written permission. Permission can
be requested from the address below.

[%hardbreaks]
International Electrotechnical Commission
3 rue de Varembé
PO Box 131
CH-1211 Geneva 20, Switzerland
mailto:terminology@iec.ch[terminology@iec.ch]
https://www.iec.ch/[www.iec.ch]
