source: _source

title: "IEV Electropedia Glossarist demo"

google_analytics:
  id: UA-169198783-1

committee:
  main_logo:
    path: assets/images/IEC_logo.svg
  footer_logo:
    path: assets/images/IEC_logo.svg
    url: https://www.iec.ch/

font_awesome_kit_url: https://kit.fontawesome.com/77a8a07e0a.js

# This is to convert jekyll-asciidoc math into real MathML
asciimath_delimiter: "\\$"

has_brand_name: yes
always_show_committee_link_on_landing: yes

email: open.source@ribose.com

tagline: "Electropedia: The World's Online Electrotechnical Vocabulary"

description: >-
  Electropedia is produced by the IEC, the world’s leading organization
  that prepares and publishes International Standards for all
  electrical, electronic and related technologies – collectively known
  as “electrotechnology”. Electropedia (also known as the "IEV Online")
  contains all the terms and definitions in the International
  Electrotechnical Vocabulary or IEV which is published also as a set of
  publications in the IEC 60050 series that can be ordered separately
  from the IEC webstore.

# Used for copyright notice and possibly more.
org:
  name: International Electrotechnical Commission
  website:
    url: https://www.iec.ch/
    title: www.iec.ch
  email: terminology@iec.ch
  address: |-
    3 rue de Varembé
    PO Box 131
    CH-1211 Geneva 20, Switzerland

baseurl: ""
url: "https://iev.geolexica.org"

social:
  links:
    - url: https://twitter.com/IEC
    - url: https://github.com/glossarist/iev-demo-site

# algolia:
#   application_id: NOP
#   index_name: NOP
#   search_only_api_key: NOP

nav:
  items:
  - id: concepts
    url: /concepts
    title: Concepts
    description: List of all concepts
  - id: posts
    url: /posts
    title: News & Articles
  - id: stats
    url: /stats
    title: Statistics
    description: Per-language term statistics
  - id: about
    url: /about
    title: About

footer_nav:
  - url: https://www.iec.ch/dyn/www/f?p=103:7:0::::FSP_ORG_ID,FSP_LANG_ID:1231,25
    title: IEC TC 1

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

theme: jekyll-geolexica

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  domains:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      show_header_meta: true

geolexica:
  concepts_glob: "../iev-data/concepts/concept-*.yaml"
  concept_date_format: "%Y-%m"
  math: true
  term_languages:
    - eng
    - fra
    - ara
    - ces
    - deu
    - fin
    - ita
    - jpn
    - kor
    - mon
    - nld
    - nno
    - nob
    - pol
    - por
    - rus
    - slv
    - spa
    - srp
    - swe
    - zho
  formats:
    - html
    - json
    - json-ld
    - tbx-iso-tml
    - turtle
    - yaml

tidy_json:
  pretty: true
  continue_on_error: true

plugins:
  - jekyll-asciimath
  - jekyll-data
  - jekyll-feed
  - jekyll-geolexica
  - jekyll-plugin-frontend-build
  - jekyll-sitemap
  - jekyll-tidy-json
