title: "ISO/TC 211 Geolexica"

google_analytics:
  id: UA-138578173-2

committee:
  id: 211
  name: Geographic information/Geomatics
  home: https://committee.iso.org/home/tc211

font_awesome_kit_url: https://kit.fontawesome.com/77a8a07e0a.js

has_brand_name: yes
always_show_committee_link_on_landing: yes

email: open.source@ribose.com

tagline: >-
  The authoritative
  geographic information terminology database

description: >-
  The authoritative glossary for geographic information technology from ISO/TC 211.

# Used for copyright notice and possibly more.
org:
  name: International Organization for Standardization
  website:
    url: https://www.iso.org/
    title: www.iso.org
  email: copyright@iso.org
  address: |-
    Chemin de Blandonnet 8
    CP 401
    1214 Vernier, Geneva
    Switzerland

baseurl: ""
url: "https://www.geolexica.org"

social:
  links:
    - url: https://twitter.com/ISOTC211
    - url: https://github.com/ISO-TC211
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

# algolia:
#   application_id: NOP
#   index_name: NOP
#   search_only_api_key: NOP

nav:
  items:
  - id: concepts
    url: /concepts
    title: Concepts
    description: List of all concepts
  - id: posts
    url: /posts
    title: News & Articles
  - id: registers
    url: /registers
    title: Registers
    description: Language registries of the Multi-Lingual Glossary of Terms
  - id: stats
    url: /stats
    title: Statistics
    description: Per-language term statistics
  - id: about
    url: /about
    title: About
  - id: feedback
    url: /feedback
    title: Feedback

footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: ISO/TC 211

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

theme: jekyll-geolexica

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  concepts:
    output: true
    permalink: /:collection/:name/
  concepts_json:
    output: true
    output_ext: .json
    permalink: /api/concepts/:name.json
  concepts_jsonld:
    output: true
    output_ext: .jsonld
    permalink: /api/concepts/:name.jsonld
  concepts_ttl:
    output: true
    output_ext: .ttl
    permalink: /api/concepts/:name.ttl

defaults:
  - scope:
      path: ""
      type: "concepts"
    values:
      layout: concept
  - scope:
      path: ""
      type: "concepts_json"
    values:
      layout: concept.json
      permalink: /api/concepts/:name.json
  - scope:
      path: ""
      type: "concepts_jsonld"
    values:
      layout: concept.jsonld
      permalink: /api/concepts/:name.jsonld
  - scope:
      path: ""
      type: "concepts_ttl"
    values:
      layout: concept.ttl
      permalink: /api/concepts/:name.ttl

geolexica:
  concepts_glob: "./iev-data/concepts/concept-*.yaml"
  term_languages:
    - eng
    - ara
    - chn
    - dan
    - dut
    - fin
    - fra
    - ger
    - jpn
    - kor
    - msa
    - pol
    - rus
    - spa
    - swe

exclude:
  - geolexica-database/
  - README.adoc

  - "*.xlsx"
  - "*.yaml"
  - concepts_data
  - mlgt-data

  - Gemfile
  - Gemfile.lock
  - Makefile

  - babel.config.js
  - package.json
  - package-lock.json
  - monitor.sh
  - node_modules

  - github_deploy_key.enc
  - deploy.sh
  - monitor.sh

  - .sass-cache/

  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
