name: deploy

on:
  push:
    branches:
      - master
      - staging
  repository_dispatch:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
      url: ${{ github.ref == 'refs/heads/master' && 'https://iev.geolexica.org' || 'https://iev-staging.geolexica.org' }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev openssl
      - name: Setup snaps
        run: |
          sudo snap install yq
          sudo snap install aws-cli --classic
          sudo snap install node --classic --channel=10/stable
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup npm
        run: |
          npm install
      - name: Fetch concepts
        run: |
          make iev-data
      - name: Build site
        run: |
          make _site

      - name: Deploy to geolexica.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws configure set default.s3.max_concurrent_requests 100
          aws configure set default.s3.max_queue_size 10000
          aws configure set default.s3.use_accelerate_endpoint true
          aws configure set default.s3.payload_signing_enabled false
          rake geolexica:s3_deploy
